### PR TITLE
Adding Support for WPCLI

### PR DESCRIPTION
**Pull request by Basilakis**
Adding WPCLI Support to freemius fixer.

`wp FS_CLI fs_cleanup`

### CODE REVIEW

**Comment by Basilakis** [comment]
@vovafeldman Could you please review and approve if possible? :)

**Comment by Basilakis** [comment]
@vovafeldman nudge :)

**Comment by vovafeldman** [comment]
Hey @Basilakis 👋  Could you please explain what is the purpose (or use case) of adding CLI support for the fixer? The reason I'm asking is that the fixer exists for edge cases issues, it is not a tool that should be used as part of some intentional process.

**Comment by Basilakis** [comment]
@vovafeldman For those edge cases, we need to pull or run without any customer interaction ( to fix their issues ).

If possible to merge all good, if not, we will still be using it and keep putting open source hours to it, as a fork, but we already have others using this and asked us also if possible to make it official.

**Pull request closed without merging**
